# Generated by Django 2.0.5 on 2018-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonToRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_month', models.PositiveIntegerField(blank=True, null=True)),
                ('birthday', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
