# Generated by Django 2.0.5 on 2018-05-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontoregister',
            name='SSN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
